dotnet/docs.pl-pl

- docs/csharp/language-reference/preprocessor-directives/preprocessor-else.md
https://github.com/dotnet/docs.pl-pl/pull/6
> Perconey patch 2

- docs/csharp/programming-guide/generics/constraints-on-type-parameters.md
https://github.com/dotnet/docs.pl-pl/pull/1
> Vmati patch 1

- docs/csharp/language-reference/operators/dereference-operator.md
https://github.com/dotnet/docs.pl-pl/pull/35
> Perconey patch 21

- docs/csharp/language-reference/operators/logical-negation-operator.md
https://github.com/dotnet/docs.pl-pl/pull/36
> Perconey patch 22

- docs/csharp/language-reference/operators/decrement-operator.md
https://github.com/dotnet/docs.pl-pl/pull/33
> Perconey patch 19

- docs/csharp/language-reference/operators/increment-operator.md
https://github.com/dotnet/docs.pl-pl/pull/32
> Perconey patch 18

- docs/csharp/language-reference/keywords/by.md
https://github.com/dotnet/docs.pl-pl/pull/41
> Perconey patch 27

- docs/csharp/language-reference/operators/right-shift-assignment-operator.md
https://github.com/dotnet/docs.pl-pl/pull/40
> Perconey patch 26

- docs/csharp/language-reference/operators/conditional-and-operator.md
https://github.com/dotnet/docs.pl-pl/pull/37
> Perconey patch 23

- docs/csharp/language-reference/operators/assignment-operator.md
https://github.com/dotnet/docs.pl-pl/pull/38
> Perconey patch 24

- docs/csharp/language-reference/operators/invocation-operator.md
https://github.com/dotnet/docs.pl-pl/pull/30
> Perconey patch 16

- docs/csharp/language-reference/operators/null-conditional-operators.md
Fix language mistakes and sentences
> Fix translation of topic to PL

- docs/csharp/programming-guide/index.md
Hi,
I would like to propose these changes, but I am not sure if I should update `ms.date` or `ms.lasthandoff`. Should I do this?
I am also wondering if I can change link' texts only in this one file, because it may introduce a bit of inconsistency. But, on the other hand, I would have to change the link' texts in many other files and therefore make a quite large PR.
> Update index.md in csharp/programming-guide

- docs/csharp/language-reference/compiler-messages/cs0616.md
https://github.com/dotnet/docs.pl-pl/pull/93
> Perconey patch 63

- docs/csharp/language-reference/compiler-messages/cs0826.md
https://github.com/dotnet/docs.pl-pl/pull/96
> Perconey patch 66

- docs/csharp/language-reference/compiler-messages/cs0834.md
https://github.com/dotnet/docs.pl-pl/pull/97
> Perconey patch 67

- docs/csharp/language-reference/compiler-messages/cs0845.md
https://github.com/dotnet/docs.pl-pl/pull/100
> Perconey patch 70

- docs/csharp/language-reference/compiler-messages/cs1501.md
https://github.com/dotnet/docs.pl-pl/pull/108
> Perconey patch 77

- docs/csharp/language-reference/compiler-messages/cs1567.md
https://github.com/dotnet/docs.pl-pl/pull/109
> Perconey patch 78

- docs/csharp/language-reference/compiler-messages/cs1640.md
https://github.com/dotnet/docs.pl-pl/pull/110
> Perconey patch 79

- docs/standard/exceptions/how-to-create-user-defined-exceptions.md
https://github.com/dotnet/docs.pl-pl/pull/117
> P system patch 1

- docs/csharp/language-reference/compiler-messages/cs1674.md
https://github.com/dotnet/docs.pl-pl/pull/119
> Perconey patch 81

- docs/csharp/language-reference/compiler-messages/cs1716.md
https://github.com/dotnet/docs.pl-pl/pull/128
> Perconey patch 84

- docs/visual-basic/language-reference/statements/end-keyword-statement.md
https://github.com/dotnet/docs.pl-pl/pull/157
> Warchlak patch 15

- docs/visual-basic/language-reference/statements/into-clause.md
https://github.com/dotnet/docs.pl-pl/pull/140
> Warchlak patch 2

- docs/visual-basic/developing-apps/printing/how-to-print-a-form-by-using-the-printform-component.md
https://github.com/dotnet/docs.pl-pl/pull/176/
> Warchlak patch 10

- docs/csharp/index.md
The translation was made by hand from original English file.
> Updated translation of index.md

- docs/csharp/index.md
- docs/csharp/tutorials/intro-to-csharp/index.md
> Translation fixes in docs\csharp\index.md

- docs/csharp/index.yml
Small visual correct so it looks like all other articles on page.
> Change lowercase letter to uppercase
